language: csharp
solution: src/Bitretsmah.sln
install:
  - nuget restore src/Bitretsmah.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Bitretsmah.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Bitretsmah.Tests.Unit/bin/Release/Bitretsmah.Tests.Unit.dll
branches:
  only:
    - master
    - develop
notifications:
  email:
    on_success: never
    on_failure: always