language: csharp
solution: src/Bitretsmah.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test src/Bitretsmah.Tests.Unit/Bitretsmah.Tests.Unit.csproj
branches:
  only:
    - master
    - develop
notifications:
  email:
    on_success: never
    on_failure: always