language: csharp

solution: src/Bitretsmah.sln

install:
  - nuget restore src/Bitretsmah.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
  - chmod +x set_assembly_version.sh merge-assemblies.sh

script:
  - ./set_assembly_version.sh
  - xbuild /p:Configuration=Release src/Bitretsmah.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./src/Bitretsmah.Tests.Unit/bin/Release/Bitretsmah.Tests.Unit.dll
  - ./merge-assemblies.sh

notifications:
  email:
    on_success: change
    on_failure: change